# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: jenkins-pod-lister
#   namespace: jenkins # Ensure this matches your Jenkins namespace
# rules:
#   - apiGroups: [""] # "" indicates the core API group
#     resources: ["pods"]
#     verbs: ["list", "get"] # Add "get" if Jenkins also needs to retrieve individual pod details
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: jenkins-namespace-lister
# rules:
#   - apiGroups: [""]
#     resources: ["namespaces"]
#     verbs: ["list"]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: cluster-replicationcontrollers-reader
# rules:
#   - apiGroups: [""]
#     resources: ["replicationcontrollers"]
#     verbs: ["list", "get"]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: jenkins-all-lister-role
#   namespace: jenkins # Ensure this matches your Jenkins namespace
# rules:
#   - apiGroups: ["*"] # "" indicates the core API group
#     resources: [""]
#     verbs: ["*"] # Add "get" if Jenkins also needs to retrieve individual pod details
# ---